### ISSUE TITLE
Fail to build with Sourcery CodeBench Lite 2013.11

### ISSUE THREAD

**Issue by jserv** [EmcraftSystems/u-boot#3]
I was attempting to build `u-boot` with [Sourcery CodeBench Lite](http://www.mentor.com/embedded-software/sourcery-tools/sourcery-codebench/editions/lite-edition/) ARM EABI version 2013.11. GCC complains as following:

```
arm-none-eabi-gcc  -g  -Os   -g2 -mthumb -mcpu=cortex-m3 -fsigned-char -O2 -fno-builtin-puts -fno-common -ffixed-r8 -D__KERNEL__ -I/tmp/u-boot/include -fno-builtin -ffreestanding -isystem /usr/local/csl/arm-2013.11/bin/../lib/gcc/arm-none-eabi/4.8.1/include -pipe  -DCONFIG_ARM -D__ARM__ -DCONFIG_MEM_NVM_BASE="0x00000000" -DCONFIG_MEM_NVM_LEN="(1024 * 1024 * 2)" -DCONFIG_MEM_NVM_UBOOT_OFF="0x0" -DCONFIG_MEM_RAM_BASE="0x20000000" -DCONFIG_MEM_RAM_LEN="(20 * 1024)" -DCONFIG_MEM_RAM_BUF_LEN="(88 * 1024)" -DCONFIG_MEM_MALLOC_LEN="(16 * 1024)" -DCONFIG_MEM_STACK_LEN="(4 * 1024)" -I/tmp/u-boot/cpu/arm_cortexm3 -Wall -Wstrict-prototypes -fno-stack-protector   -o cmd_cptf.o cmd_cptf.c -c
In file included from /usr/local/csl/arm-2013.11/lib/gcc/arm-none-eabi/4.8.1/include/stdint.h:11:0,
                 from /usr/local/csl/arm-2013.11/lib/gcc/arm-none-eabi/4.8.1/include-fixed/sys/cdefs.h:54,
                 from /usr/local/csl/arm-2013.11/arm-none-eabi/include/string.h:12,
                 from cmd_cptf.c:23:
/usr/local/csl/arm-2013.11/lib/gcc/arm-none-eabi/4.8.1/include/stdint-gcc.h:40:24: error: conflicting types for 'int32_t'
 typedef __INT32_TYPE__ int32_t;
                        ^
In file included from /tmp/u-boot/include/common.h:39:0,
                 from cmd_cptf.c:21:
/tmp/u-boot/include/linux/types.h:102:17: note: previous declaration of 'int32_t' was here
 typedef  __s32  int32_t;
```

The workaround is to remove `#include <string.h>` in file `cpu/arm_cortexm3/cmd_cptf.c`.
